/**
 * Converts the Claude Design export `_ds_bundle.js` into an ES module.
 *
 * The export is an IIFE that expects a global `React` and hangs its components
 * off `window.HomeAssistDesignSystem_<hash>`. Neither works during the
 * server-side prerender, so this rewrites it into `src/ds/index.js`:
 *   - `import React from 'react'` instead of the global
 *   - a plain local namespace object instead of the window assignment
 *   - named + default ES exports
 *
 * Re-run this (via `npm run prepare:ds`) whenever you re-export the design
 * system from Claude Design and drop a new `_ds_bundle.js` in `scripts/`.
 */
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const SRC = resolve(here, '_ds_bundle.js');
const OUT = resolve(here, '../src/ds/index.js');

const raw = readFileSync(SRC, 'utf8');

// Pull the namespace name out of the bundle header comment.
const nsMatch = raw.match(/"namespace"\s*:\s*"([^"]+)"/);
if (!nsMatch) throw new Error('build-ds: could not find namespace in _ds_bundle.js');

// Swap the window-backed namespace for a local object.
const windowLine =
  /const __ds_ns = \(window\.[A-Za-z0-9_]+ = window\.[A-Za-z0-9_]+ \|\| \{\}\);/;
if (!windowLine.test(raw)) {
  throw new Error('build-ds: bundle preamble changed shape — inspect _ds_bundle.js before rebuilding');
}
let body = raw.replace(windowLine, 'const __ds_ns = {};');

// Serve Lucide icons from our own origin instead of unpkg.com.
// See scripts/vendor-icons.mjs, which populates public/icons/.
const cdnPattern = /['"]https:\/\/unpkg\.com\/lucide-static@[^'"]*['"]/g;
const cdnHits = (body.match(cdnPattern) || []).length;
body = body.replace(cdnPattern, "'/icons/'");

// Component names, in export order, straight from the bundle manifest.
const manifest = JSON.parse(raw.match(/\/\* @ds-bundle:\s*(\{[\s\S]*?\})\s*\*\//)[1]);
const names = manifest.components.map((c) => c.name);

const out = `// GENERATED by scripts/build-ds.mjs — do not edit by hand.
// Source: scripts/_ds_bundle.js (Claude Design export, namespace ${nsMatch[1]})
import React from 'react';

${body}

const DS = __ds_ns_export;
export default DS;
export const {
${names.map((n) => `  ${n},`).join('\n')}
} = DS;
`;

// The IIFE closes over __ds_ns; expose it to module scope.
const withExport = out.replace(
  /^\(\(\) => \{$/m,
  'let __ds_ns_export;\n(() => {'
).replace(
  /^\}\)\(\);$/m,
  '  __ds_ns_export = __ds_ns;\n})();'
);

mkdirSync(dirname(OUT), { recursive: true });
writeFileSync(OUT, withExport, 'utf8');
console.log(
  `build-ds: wrote ${names.length} components to src/ds/index.js ` +
  `(rewrote ${cdnHits} unpkg icon URL${cdnHits === 1 ? '' : 's'} to /icons/)`
);
